pybo/views/memo.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from sqlalchemy import func

from .. import db
from ..forms import QuestionForm, AnswerForm, memoForm
from ..models import Question, Answer, User, question_voter, memo_Question
from ..views.auth_views import login_required

bp = Blueprint('memo', __name__, url_prefix='/memo')


@bp.route('/memolist/',methods=('GET', 'POST'))
def _list():
    page=request.args.get('page', type=int, default = 1)
    form = memoForm()
    memo_list = memo_Question.query.order_by(memo_Question.memo_create_date.desc())
    memo_list = memo_list.paginate(page,per_page=11)
    return render_template('memo/memo.html',memo_list=memo_list, form=form)

@bp.route('/detail/<int:memo_id>/')
def detail(memo_id):
    memo = memo_Question.query.get_or_404(memo_id)
    return render_template('memo/memo_detail.html',memo=memo)

@bp.route('/create/', methods=('POST','GET'))
@login_required
def create():
    form = memoForm()
    content=request.form['content']
    memo=memo_Question(content=content, memo_create_date=datetime.now(), user=g.user)
    db.session.add(memo)
    db.session.commit()
    return redirect(url_for('memo._list'))



@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

import os
from flask import send_from_directory

@bp.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')

pybo/templates/memo/memo.html
{% extends 'base.html' %}
{% block content %}
<html>
    <head>
        <!--메모입력창 스크립트-->
        <script src="C:\projects\myproject\pybo\static\jquery-3.5.1.min.js"></script>
        <script>
            function popupOpen(){
                var $layerPopupObj = $('#popup');
                var left = ( $(window).scrollLeft() + ($(window).width() - $layerPopupObj.width()) / 2 );
                var top = ( $(window).scrollTop() + ($(window).height() - $layerPopupObj.height()) / 2 );
                $layerPopupObj.css({'left':left,'top':top, 'position':'absolute'});
                $('body').css('position','relative').append($layerPopupObj);

                if(document.all.popup.style.visibility=="hidden") {
                    document.all.popup.style.visibility="visible";
                    bgLayerOpen();
                    return false;
                }else{
                    document.all.popup.style.visibility="hidden";
                    bgLayerClear();
                    return false;
                }

            }

            function bgLayerOpen() {
                if(!$('.bgLayer').length) {
                    $('<div class="bgLayer"></div>').appendTo($('body'));
                }
                var object = $(".bgLayer");
                var w = $(document).width()+12;
                var h = $(document).height();


                object.css({'width':w,'height':h});
                object.fadeIn(500);   //생성되는 시간 설정
                $('html').css("overflow", "hidden");

            }

            function bgLayerClear(){
                var object = $('.bgLayer');



            if(object.length) {
                object.fadeOut(500, function() {
                object.remove();

            });

                }

                $('html').css("overflow", "scroll");
            }
            $(function(){

                $(window).resize(function() { //화면 크기 변할 시
                    $('.bgLayer').css('width' ,  $(window).width() - 0 );
                    $('.bgLayer').css('height' ,  $(window).height() - 0 );
                });

            });
            $(document).ready(function() {
                $('#memo').on('keyup', function() {
                    $('#test_cnt').html("("+$(this).val().length+" / 200)");

                    if($(this).val().length > 200) {
                        $(this).val($(this).val().substring(0, 200));
                        $('#test_cnt').html("(200 / 100)");
                    }
                });
            });

        </script>
        <style type="text/css">
            *{margin: 0;}
            body{margin: 0 auto;}
            /*메모 게시판 css*/
            .warp{ height: 100%; width: 1000px; margin: 0 auto; padding: 0; display: flex; justify-content: flex-start; flex-direction: row; flex-wrap: wrap; align-content: space-around;}
            .title{ width: 1000px; margin: 20px 0; margin-top: 40px; padding-bottom:5px; border-bottom: 2px solid #3A9D5F; color: #3A9D5F; background-color: white;}
            .memo-button{display:block; height: 238px; width: 238px; text-align: center; margin: 5px; background-color: #3A9D5F; border-radius: 30px; color: white; border:0 solid white;}
            .memo-box{display:flex; justify-content: center; align-content: center; height: 238px; width: 238px; text-align: center; margin: 5px; background-color: white; border-radius: 30px; color: #3A9D5F; border:1px solid #3A9D5F;}
            .memo-box a{margin:auto; width: 200px; text-decoration: none; color: #3A9D5F; overflow: hidden; word-break: break-all;}
            /*팝업창 css*/
            #popup{overflow:hidden; height:400px; display:block; background-color: white; border:2px solid #3A9D5F; border-radius:40px; border-color: #3A9D5F; width:400px; z-index:100; position:absolute;  top:20%; left:10%;}
            .close {display:block; margin-left: auto; padding-top:15px; padding-right:20px; padding-bottom: 10px; color:#3A9D5F; text-decoration: none;}
            .textbox {display:flex; justify-content: center; flex-direction: column; }
            .popCont{background: white; color: #3A9D5F; text-align: center;margin: auto;}
            .popCont #memo{
                height:250px; width:300px; display:block; margin:auto; font-size:12px; border:0 solid white; text-align: center;resize: none;
            }
            .popCont #submit{display:block; margin: auto; margin-top: 20px; background-color: #3A9D5F; border-radius: 30px; color: white; padding:5px 15px;border:0 solid white;}
            .bgLayer {display:none;position:absolute; top:0; left:0; width:100%; height:100%; background:#000; opacity:.5; filter:alpha(opacity=50); z-index:10;}  /* z-index가 10이다. 이보다 위에 보이기 위해선 팝을 이보다 크게 설정해야한다. */
            textarea:focus {outline: none;}
        </style>
    </head>
    <body>
        <!--메모 게시판 시작-->
        <div class="warp">
            <!--타이틀과 네이게이터 간격 조정은 title 스타일의 margin-top 조절-->
            <div class="title">
                <p>메모 게시판</p>
            </div>
            <button class="memo-button" onclick="popupOpen()" >메모 작성하기</button>
            <!--if문으로 게시판 한 줄 씩 늘어나듯이 박스 늘어나는 문장 필요, 아래의 박스들은 하나씩 늘릴때마다 옆으로 늘어나고 4개가 넘으면 아래에서부터 다시 늘어납니다.-->
            {% if memo_list %}
                {% for memo in memo_list.items %}
                <ul>
                    <li class="memoli"><div class="memo-box"><a href="{{ url_for('memo.detail', memo_id=memo.memo_id) }}">{{ memo.content}}</a></div></li>

                </ul>
                {% endfor %}
            {% else %}
            <p>노질문</p>
            {% endif %}

        </div>
        <!--박스 늘어나는 문장 필요-->


        <!--메모 게시판 끝-->

        <!--팝업창 시작-->
        <div class="popup" id="popup" style="position:absolute;  visibility:hidden;">
                 <div class="textbox">
                    <a href="#" class="close" onClick="javascript:popupOpen()">X</a></div>
                    <form action="{{url_for('memo.create')}}"class="popCont" method="post">
                        {{ form.csrf_token }}
                        <textarea id="memo" type="text" name="content" rows="1"maxlength="200" placeholder="메모를 작성하시오." onfocus="this.placeholder=''" onblur="this.placeholder='메모를 작성하시오.'"></textarea>
                        <div id="test_cnt" style="font-size:10pt";>(0 / 200)</div>
                        <input type="submit" id="submit" name="저장" value="메모등록">
                    </form>
                </div>
        </div>
        <!--팝업창 끝-->
    <!--페이징처리시작-->
            <ul class="pagination justify-content-center">
                <!--이전페이지-->
                {% if memo_list.has_prev %}
                <li class="page-item">
                    <a class="page-link" href="?page={{memo_list.prev_num }}">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                {% for page_num in memo_list.iter_pages() %}
                    {% if page_num %}
                        {% if page_num != memo_list.page %}
                        <li class="page-item">
                            <a class = "page-link" href="?page={{page_num}}">{{page_num}}</a>
                        </li>
                        {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{page_num}}</a>
                        </li>
                        {% endif %}
                    {% else %}
                        <li class="disabled">
                            <a class="page-link" href="#">...</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <!-- 다음페이지-->
                {% if memo_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{memo_list.next_num}}">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!--페이징처리 끝-->
    </body>
</html>
{% endblock %}

pybo/templates/memo/memo_detail.html
{% extends 'base.html' %}
{% block content %}
    <head>

        <style>

            @font-face{
                    src: url("/SCDream4.otf");
                    font-family: "SCDream4";
                }
            *{margin: 0;
            }
            body{margin: 0 auto;}
            .warp {height: 100%; width: 1000px; margin: 0 auto; padding: 0; display: flex; justify-content: center; flex-direction: column; flex-wrap: wrap; align-content: center;}
            .title{ width: 1000px; margin: 20px 0; margin-top: 40px; padding-bottom:5px; border-bottom: 2px solid #3A9D5F; color: #3A9D5F; background-color: white;}
            .memo-box {height: 400px; width: 400px; text-align: center; margin: auto; background-color: white; border-radius: 30px; color: #3A9D5F; border:1px solid #3A9D5F; display: flex; flex-direction: column; justify-content: space-around; align-content: space-around;}
            .close {background-color: #3A9D5F; height: 50px; width:50px; border-radius: 100px; margin: auto; margin-top : 20px; display: flex; flex-direction: column; justify-content: space-around; align-content: space-around;}
            .close a{margin: auto; color:white; text-decoration: none;}
            .memo-detail{margin: auto;}


            </style>
    </head>
    <body>

        <div class="warp">
            <div class="title">
                <p>자세히</p>
            </div>

            <div class="memo-box">
                <div class="memo-detail">
                    {{ memo.content }}
                </div>
            </div>

            <div class="close">
                <a href="{{url_for('memo._list')}}">X</a>
            </div>
        </div>
    </body>
</html>
{% endblock %}