pybo/views/gomin_answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect
from pybo import db
from ..forms import AnswerForm
from pybo.models import Gomin, Gomin_Answer
from .auth_views import login_required

bp = Blueprint('gomin_answer',__name__,url_prefix='/gomin_answer')

@bp.route('/create/<int:gomin_id>',methods=('POST',))
@login_required
def create(gomin_id):
    form = AnswerForm()
    gomin = Gomin.query.get_or_404(gomin_id)
    if form.validate_on_submit():
        content = request.form['content']
        gomin_answer = Gomin_Answer(content=content, create_date=datetime.now(), user=g.user)
        gomin.gomin_answer_set.append(gomin_answer)
        db.session.commit()
        return redirect(url_for('gomin.detail', gomin_id=gomin_id))
    return render_template('gomin/gomin_detail.html', gomin=gomin, form=form)
    gomin = Gomin.query.get_or_404(gomin_id)
    content = request.form['content']
    gomin_answer = Gomin_Answer(content=content, create_date=datetime.now(), user=g.user)
    gomin.gomin_answer_set.append(gomin_answer)
    db.session.commit()
    return redirect(url_for('gomin.detail',gomin_id=gomin_id))

@bp.route('/modify/<int:answer_id>', methods=('GET','POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        form = AnswerForm(obj=answer)
        return render_template('answer/answer_form.html', answer=answer, form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/gomin_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from sqlalchemy import func

from .. import db
from ..forms import QuestionForm, AnswerForm, GominForm, Gomin_AnswerForm
from ..models import Question, Answer, User, question_voter, Gomin, Gomin_Answer
from ..views.auth_views import login_required

bp = Blueprint('gomin', __name__, url_prefix='/gomin')


@bp.route('/gominlist/')
def _list():
    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    so = request.args.get('so', type=str, default='recent')

    # 정렬
    if so == 'recommend':
        sub_query = db.session.query(gomin_voter.c.gomin_id, func.count('*').label('num_voter')) \
            .group_by(gomin_voter.c.gomin_id).subquery()
        gomin_list = Gomin.query \
            .outerjoin(sub_query, Gomin.id == sub_query.c.gomin_id) \
            .order_by(sub_query.c.num_voter.desc(), Gomin.create_date.desc())
    elif so == 'popular':
        sub_query = db.session.query(Gomin_Answer.gomin_id, func.count('*').label('num_answer')) \
            .group_by(Gomin_Answer.gomin_id).subquery()
        gomin_list = Gomin.query \
            .outerjoin(sub_query, Gomin.id == sub_query.c.gomin_id) \
            .order_by(sub_query.c.num_answer.desc(), Gomin.create_date.desc())
    else:  # recent
        gomin_list = Gomin.query.order_by(Gomin.create_date.desc())

    # 조회
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Gomin_Answer.gomin_id, Gomin_Answer.content, User.username) \
            .join(User, Gomin_Answer.user_id == User.id).subquery()
        gomin_list = gomin_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.gomin_id == Gomin.id) \
            .filter(Gomin.subject.ilike(search) |  # 질문제목
                    Gomin.content.ilike(search) |  # 질문내용
                    User.username.ilike(search) |  # 질문작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()

    # 페이징
    gomin_list = gomin_list.paginate(page, per_page=10)
    return render_template('gomin/gomin_list.html', gomin_list=gomin_list, page=page, kw=kw, so=so)



@bp.route('/detail/<int:gomin_id>/')
def detail(gomin_id):
    form = Gomin_AnswerForm()
    gomin = Gomin.query.get_or_404(gomin_id)
    return render_template('gomin/gomin_detail.html', gomin=gomin, form=form)


@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = GominForm()
    if request.method == 'POST' and form.validate_on_submit():
        gomin = Gomin(subject=form.subject.data, content=form.content.data,
                            create_date=datetime.now(), user=g.user)
        db.session.add(gomin)
        db.session.commit()
        return redirect(url_for('gomin._list'))#제출하면 redirect로 question리스트로 리턴하도록함
    return render_template('gomin/gomin_form.html', form=form)


@bp.route('/modify/<int:gomin_id>', methods=('GET', 'POST'))
@login_required
def modify(gomin_id):
    gomin = Gomin.query.get_or_404(gomin_id)
    if g.user != gomin.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('gomin.detail', gomin_id=gomin_id))
    if request.method == 'POST':
        form = GominForm()
        if form.validate_on_submit():
            form.populate_obj(gomin)
            gomin.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('gomin.detail', gomin_id=gomin_id))
    else:
        form = GominForm(obj=gomin)
    return render_template('gomin/gomin_form.html', form=form)


@bp.route('/delete/<int:gomin_id>')
@login_required
def delete(gomin_id):
    gomin = Gomin.query.get_or_404(gomin_id)
    if g.user != gomin.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('gomin.detail', gomin_id=gomin_id))
    db.session.delete(gomin)
    db.session.commit()
    return redirect(url_for('gomin._list'))

import os
from flask import send_from_directory

pybo/templates/gomin/gomin_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ gomin.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ gomin.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ gomin.user.username }}</div>
                    <div>{{ gomin.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ gomin.gomin_answer_set|length }}개의 답변이 있습니다.</h5>
    {% for gomin_answer in gomin.gomin_answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ gomin_answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ gomin_answer.user.username }}</div>
                    <div>{{ gomin_answer.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('gomin_answer.create', gomin_id=gomin.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea {% if not g.user %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

pybo/templates/gomin/gomin_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.data or '' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

pybo/templates/gomin/gomin_list.html
{% extends 'base.html' %}
{% block content %}
<div class = "container my-3">
    <div class="row justify-content-end my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so=='recent' %}selected{% endif %}>최신순</option>
                <option value="recommend" {% if so=='recommend' %}selected{% endif %}>추천순</option>
                <option value="popular" {% if so=='popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw or ''}}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class ="text-center thead" id="listnav">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if gomin_list %}
        {% for gomin in gomin_list.items %}
        <tr class="text-center">
            <td>{{ gomin_list.total - ((gomin_list.page-1)*gomin_list.per_page)-loop.index0 }}</td>
            <td>
                {% if gomin.voter|length > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ gomin.voter|length}}</span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{{ url_for('gomin.detail', gomin_id=gomin.id)}}">{{ gomin.subject }}</a>
                {% if gomin.answer_set|length>0 %}
                <span class = "text-danger small ml-2">{{gomin.answer_set|length}}
                {% endif %}
                </span>
            </td>
            <td>{{ gomin.user.mbti }}</td>
            <td>{{ gomin.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--페이징처리시작-->
    <ul class="pagination justify-content-center">
        <!--이전페이지-->
        {% if gomin_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="?page={{gomin_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in gomin_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != gomin_list.page %}
                <li class="page-item">
                    <a class = "page-link" data-page="?page={{page_num}}">{{page_num}}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{page_num}}</a>
                </li>
                {% endif %}
            {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지-->
        {% if gomin_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="?page={{gomin_list.next_num}}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!--페이징처리 끝-->
    <a href="{{url_for('gomin.create')}}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{{ url_for('gomin._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}