pybo/views/auth_views.py
import functools
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm
from pybo.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        mbti = form.mbti.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET','POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

pybo/views/image.py
from flask import Flask, flash, request, redirect, url_for, render_template
import urllib.request
import os
from werkzeug.utils import secure_filename
from flask import Blueprint, url_for, render_template
from werkzeug.utils import redirect

from pybo.models import Question

from flask import send_from_directory

pybo/views/main_views.py
from flask import Blueprint, url_for, render_template
from werkzeug.utils import redirect

from pybo.models import Question

import os
from flask import send_from_directory



bp = Blueprint('main',__name__,url_prefix='/')
@bp.route('/hello')
def hello_pybo():
    return 'Hello, Pybo!'

@bp.route('/')
def index():
    return render_template('mainpage/mainpage.html')

@bp.route('/introduce')
def introduce():
    return render_template('category/introduce.html')

pybo/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <link rel="icon" href="favicon.ico" type="image/x-icon" sizes="16x16">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel = "stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
    <!--pybo CSS-->
    <link rel = "stylesheet" href="{{url_for('static', filename='style.css')}}">

    <title>MBTI대나무숲 </title>

</head>
<body>
{% include "navbar.html" %}
<!--기본 템플릿에 삽입할 내용 Start-->
{% block content %}
{% endblock %}
<!--기본 템플릿에 삽입할 내용 End-->
<!--jQuery-->
<script src="{{url_for('static',filename='jquery-3.6.0.min.js')}}"></script>
<!--Bootstrap JS-->
<script src="{{url_for('static',filename='bootstrap.min.js')}}"></script>
<!--자바 스크립트 start-->
{% block script %}
{% endblock %}
<!--자바스크립트 end-->
</body>
</html>

pybo/templates/form_errors.html
<!-- 필드 오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{','.join(errors) }}
</div>
{% endfor %}
<!-- flash오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{message}}
</div>
{% endfor %}

pybo/templates/image.html
<html>
<head>
<title>Python Flask Upload and display image</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
</head>
<body>
<p><h1 align="center">Python Flask Upload and display image</h1></p>
<div class="container">
<div class="row">
    <h2>Select a file to upload</h2>
    <p>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
    </p>
    {% if filename %}
        <div>
            <img src="{{ url_for('display_image', filename=filename) }}">
        </div>
    {% endif %}
    <form method="post" action="/" enctype="multipart/form-data">
        <dl>
            <p>
                <input type="file" name="file" class="form-control" autocomplete="off" required>
            </p>
        </dl>
        <p>
            <input type="submit" value="Submit" class="btn btn-info">
        </p>
    </form>
</div>
</div>
</body>
</html>

pybo/templates/navbar.html
<!--내비게이션바-->
<style>

</style>

<div class="box" style="display:inline-block;">
    {% if g.user %}
    <ur class="nav-container2">
        <li class="nav-item2"><a href="{{ url_for('auth.logout') }}">{{ g.user.username }}(로그아웃)</a></li>
    </ur>
        {% else %}
        <ur class="nav-container2">
            <li class="nav-item2"><a href="{{ url_for('auth.signup') }}">회원가입</a></li>
            <li class="nav-item2"><a href="{{ url_for('auth.login') }}">로그인</a></li>
        </ur>
        {% endif %}
</div>
<a href="{{url_for('main.index')}}"><div class = "main-image"></div></a>
<div class="box" id="box321"style="text-align: center; display: inline-block;">

        <header>
            <div class="header">
                            <nav role="navigation">
                                <ul id="main-menu">
                                  <li><a href="#" class="category">카테고리</a>
                                    <ul id="sub-menu">
                                      <li><a href="{{ url_for('question._list')}}" aria-label="subemnu">고민 게시판</a></li>
                                      <li><a href="{{ url_for('memo._list')}}" aria-label="subemnu">메모 게시판</a></li>
                                      <li><a href="#" aria-label="subemnu">투표 게시판</a></li>
                                    </ul>
                                  </li>
                                  <li><a href="{{url_for('main.introduce')}}">소개</a></li>
                                  <li><a href="#">공지</a></li>
                                  <li><a href="#">문의</a></li>
                                </ul>
                            </nav>
            </div>
        </header>
</div>

</header>